Okay, this works.

diff --git a/coldstrap b/coldstrap
--- a/coldstrap
+++ b/coldstrap
@@ -108,22 +108,17 @@ echo; read -p "Are you sure you're sure about that? (y/n): " -n 1 -r; echo
 if [[ ! $REPLY =~ ^[Yy]$ ]]; then die; fi
 
 ## Format the disk. Unsure of sleep here, maybe sync?
-sfdisk "$DEVICE" << EOF || die "couldn't partition with sfdisk"
-1MiB,500MiB,L,*
--,-,L,-
+sfdisk "$DEVICE" << EOF && sync || die "couldn't partition with sfdisk"
+1MiB,-,L,*
 EOF
-sleep 1
 
-## Create encrypted boot and root partitions
-for i in 1 2; do
-  echo -n "$BD_PW" | cryptsetup -v luksFormat "$DEVICE$i" - &&
-    echo -n "$BD_PW" | cryptsetup open "$DEVICE$i" "part$i" - &&
-    mkfs.ext4 "/dev/mapper/part$i" ||
-    die "$LINENO: couldn't cryptsetup/mkfs/mount $DEVICE$i"
-  sleep 1 # get "remove ioctl on ... failed: device or resource busy w/o this
-  cryptsetup close "part$i"
-done
-sleep 1
+## Create bootable encrypted root partition
+echo -n "$BD_PW" | cryptsetup -v luksFormat "${DEVICE}1" - &&
+  echo -n "$BD_PW" | cryptsetup open "${DEVICE}1" "cryptroot" - &&
+  mkfs.ext4 "/dev/mapper/cryptroot" ||
+  die "$LINENO: couldn't cryptsetup/mkfs/mount ${DEVICE}1"
+sleep 1 # get "remove ioctl on ... failed: device or resource busy w/o this
+cryptsetup close cryptroot
 
 CHROOT=root.x86_64/bin/arch-chroot
 
@@ -140,9 +135,7 @@ umount root.x86_64 >/dev/null 2>&1
 sleep 1
 
 mkdir mnt
-mount "/dev/mapper/part2" mnt || die "couldn't mount part2"
-sleep 1
-mount "/dev/mapper/part1" mnt/boot || die "couldn't mount part1"
+mount "/dev/mapper/cryptroot" mnt || die "couldn't mount cryptroot"
 sleep 1
 
 root.x86_64/usr/bin/genfstab -U mnt > mnt/etc/fstab
@@ -179,12 +172,9 @@ for SCRIPT in $@; do
 done
 unset SCRIPT
 
-for i in 1 2; do
-  umount "/dev/mapper/part$i" || die "couldn't umount /dev/mapper/part$i"
-  sleep 1
-  cryptsetup close "part$i" || die "couldn't close part$i"
-  sleep 1
-done
+umount /dev/mapper/cryptroot || die "couldn't umount /dev/mapper/cryptroot"
+cryptsetup close cryptroot || die "couldn't close cryptroot"
+sleep 1
 
 umount mnt >/dev/null 2>&1
 
