Need to switch to single partition, encrypted.
Can just pass GRUB_ENABLE_CRYPTODISK, should work.

diff --git a/coldstrap b/coldstrap
--- a/coldstrap
+++ b/coldstrap
@@ -16,7 +16,7 @@ usage() {
 	  -h            show this help text
 
 	  <scripts>  additional scripts to run from in chroot following install
-  EOF
+	EOF
   echo "$TEXT"
 }
 
@@ -25,7 +25,7 @@ DEVICE=
 DESKTOP=
 PKGS=
 HOSTN=
-USERNAME=
+USER_NAME=
 SCRIPTS=
 while getopts ":d:x:p:n:u:h" opt; do
   case $opt in
@@ -42,7 +42,7 @@ while getopts ":d:x:p:n:u:h" opt; do
       HOSTN="$OPTARG"
       ;;
     u)
-      USERNAME="$OPTARG"
+      USER_NAME="$OPTARG"
       ;;
     h)
       usage && exit 0
@@ -71,13 +71,13 @@ read -rs -p "Please enter a password to encrypt the root partition with: " BD_PW
   die "couldn't get root partition password from input"
 echo
 
-if [[ -z "$USERNAME" ]]; then
+if [[ -z "$USER_NAME" ]]; then
   echo "Username not passed with -u flag"
-  read -r -p "Please enter a username for the user of the new system: " USERNAME ||
+  read -r -p "Please enter a username for the user of the new system: " USER_NAME ||
     die "couldn't get username from input"
 fi
 
-read -rs -p "Please enter a password for user '$USERNAME': " USER_PW ||
+read -rs -p "Please enter a password for user '$USER_NAME': " USER_PW ||
   die "couldn't get user password from input"
 echo; echo
 
@@ -100,15 +100,12 @@ LN=$(grep -n "## Worldwide" \
 SEDEXP="$((LN+1)),$((LN+3)){s/#Server/Server/}"
 sed -i "$SEDEXP" root.x86_64/etc/pacman.d/mirrorlist
 
-## Extra sanity before wiping the disk
-echo "Preparing to securely wipe and re-partition $DEVICE"; echo
 printf "$DEVICE is:\n\n"
 fdisk -l "$DEVICE"
-echo; read -p "Are you sure? (y/n): " -n 1 -r; echo
+echo; read -p "Are you sure about over-writing this device? (y/n): " -n 1 -r; echo
 if [[ ! $REPLY =~ ^[Yy]$ ]]; then die; fi
-
-#echo "Securely wiping $DEVICE with /dev/urandom"
-#dd if=/dev/urandom of="$DEVICE" status=progress && sync
+echo; read -p "Are you sure you're sure about that? (y/n): " -n 1 -r; echo
+if [[ ! $REPLY =~ ^[Yy]$ ]]; then die; fi
 
 ## Format the disk. Unsure of sleep here, maybe sync?
 sfdisk "$DEVICE" << EOF || die "couldn't partition with sfdisk"
@@ -117,26 +114,23 @@ sfdisk "$DEVICE" << EOF || die "couldn't partition with sfdisk"
 EOF
 sleep 1
 
-## Create filesystem on the boot partition
-mkfs.ext4 -F "${DEVICE}1" || die "$LINENO: couldn't mkfs"
+## Create encrypted boot and root partitions
+for i in 1 2; do
+  echo -n "$BD_PW" | cryptsetup -v luksFormat "$DEVICE$i" - &&
+    echo -n "$BD_PW" | cryptsetup open "$DEVICE$i" "part$i" - &&
+    mkfs.ext4 "/dev/mapper/part$i" ||
+    die "$LINENO: couldn't cryptsetup/mkfs/mount $DEVICE$i"
+  sleep 1 # get "remove ioctl on ... failed: device or resource busy w/o this
+  cryptsetup close "part$i"
+done
 sleep 1
 
-## Create encrypted root partition
-echo -n "$BD_PW" | cryptsetup -v luksFormat "${DEVICE}2" - &&
-  echo -n "$BD_PW" | cryptsetup open "${DEVICE}2" cryptroot - &&
-  mkfs.ext4 /dev/mapper/cryptroot ||
-  die "$LINENO: couldn't cryptsetup/mkfs/mount ${DEVICE}2"
-
-## Need to close and re-open encrypted partition in the chroot script
-sleep 1
-cryptsetup close cryptroot
-sleep 1
-## Unsure of sleeps here
+CHROOT=root.x86_64/bin/arch-chroot
 
 ## Script passed to chroot into bootstrap image directory
 SCRIPT=in-bootstrap-chroot.sh
 cp "$SCRIPT" "root.x86_64/usr/bin/$SCRIPT"
-root.x86_64/bin/arch-chroot root.x86_64 "$SCRIPT" "$DEVICE" "$BD_PW" ||
+echo -n "$BD_PW" | "$CHROOT" root.x86_64 "$SCRIPT" "$DEVICE" ||
   die "$SCRIPT exited"
 rm "root.x86_64/usr/bin/$SCRIPT"
 unset SCRIPT
@@ -146,9 +140,9 @@ umount root.x86_64 >/dev/null 2>&1
 sleep 1
 
 mkdir mnt
-mount /dev/mapper/cryptroot mnt || die "couldn't mount ${DEVICE}2"
+mount "/dev/mapper/part2" mnt || die "couldn't mount part2"
 sleep 1
-mount "${DEVICE}1" mnt/boot || die "couldn't mount ${DEVICE}1"
+mount "/dev/mapper/part1" mnt/boot || die "couldn't mount part1"
 sleep 1
 
 root.x86_64/usr/bin/genfstab -U mnt > mnt/etc/fstab
@@ -160,8 +154,8 @@ LOCALE=$(locale | grep 'LANG=' | sed 's/LANG=//')
 ## Usual archlinux install procedure
 SCRIPT=in-new-sys-chroot.sh
 cp "$SCRIPT" mnt/usr/bin/"$SCRIPT"
-root.x86_64/bin/arch-chroot mnt "$SCRIPT" \
-  "$DEVICE" "$TIMEZONE" "$LOCALE" "$HOSTN" "$USERNAME" "$USER_PW"
+echo -n "$USER_PW" | "$CHROOT" mnt "$SCRIPT" \
+  "$DEVICE" "$TIMEZONE" "$LOCALE" "$HOSTN" "$USER_NAME"
 rm "mnt/usr/bin/$SCRIPT"
 unset SCRIPT
 
@@ -185,12 +179,14 @@ for SCRIPT in $@; do
 done
 unset SCRIPT
 
-umount "${DEVICE}1" || die "couldn't umount ${DEVICE}1"
-sleep 1
-umount /dev/mapper/cryptroot || die "couldn't umount ${DEVICE}2"
-sleep 1
+for i in 1 2; do
+  umount "/dev/mapper/part$i" || die "couldn't umount /dev/mapper/part$i"
+  sleep 1
+  cryptsetup close "part$i" || die "couldn't close part$i"
+  sleep 1
+done
+
 umount mnt >/dev/null 2>&1
-cryptsetup close cryptroot || die "couldn't close cryptroot"
 
 echo
 echo "Voila!"
